name: iran_university_portal
description: Persian RTL university news portal for Islamic Azad University.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_riverpod: ^3.3.1
  shamsi_date: ^1.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  # path_provider_android 2.3.x pulls in package:jni, which requires Android NDK 28.
  path_provider_android: 2.2.23

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/Vazirmatn/static/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/Vazirmatn/static/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/Vazirmatn/static/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/Vazirmatn/static/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/Vazirmatn/static/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/Vazirmatn/static/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/Vazirmatn/static/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/Vazirmatn/static/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/Vazirmatn/static/Vazirmatn-Black.ttf
          weight: 900
